# ===================================================================
# EShoppingZone - Checkout Service Centralized Configuration
# ===================================================================
server.port=8089

cart.service.url=${CART_SERVICE_URL:http://localhost:8084}
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8086}
order.service.url=${ORDER_SERVICE_URL:http://localhost:8085}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8087}

# Checkout Service Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.checkoutService.base-config=default

info.app.name=Checkout Service
info.app.description=EShoppingZone Checkout Orchestrator Microservice
info.app.version=1.0.0
